/**
 * IOE Memory System
 * Intelligent Operations Engine - 6-Layer Memory Hierarchy + Dream Consolidation Engine
 *
 * Design:
 * - L1 Managed  (highest priority) → enterprise/MDM policy files
 * - L2 Project                     → NETWORK.md at repository root
 * - L3 Rules                       → domain-specific rules files
 * - L4 User                        → operator preference files
 * - L5 Local                       → per-directory auto-discovery
 * - L6 Dream   (lowest priority)   → auto-generated by DreamEngine
 *
 * Layer cascade: higher-priority layers shadow lower-priority entries on
 * conflict. During resolution the first non-empty match from L1→L6 wins.
 *
 * Persistence: every write flushes a single append-only JSONL shard per
 * layer, keeping individual shard sizes manageable. On startup, all shards
 * are replayed into an in-memory index.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';
import {
  MemoryLayer,
  MemoryEntry,
  DreamConfig,
  DomainType,
} from '../types';

// ============================================================================
// Supplementary types local to this module
// ============================================================================

/** Categories of telecom-specific long-term memory managed by DreamEngine. */
export type TelecomMemoryType =
  | 'event_memory'     // Historical faults, alerts, and remediation actions
  | 'network_memory'   // Baselines, topology patterns, KPI norms
  | 'operator_memory'  // Engineer workflow preferences, escalation contacts
  | 'org_memory';      // SOPs, regulatory obligations, change-freeze calendars

/** A single telecom-typed memory fact produced or managed by DreamEngine. */
export interface TelecomMemoryFact {
  id: string;
  type: TelecomMemoryType;
  /** ISO-8601 date the fact was first observed. */
  observedAt: string;
  /** Short human-readable summary (kept under 120 chars for index compactness). */
  summary: string;
  detail: string;
  domain?: DomainType;
  confidence: number;   // 0–1
  usageCount: number;
  tags: string[];
}

/** Options accepted by {@link MemorySystem.search}. */
export interface MemorySearchOptions {
  domain?: DomainType;
  tags?: string[];
  minImportance?: number;
  layers?: MemoryLayer[];
  limit?: number;
}

/** Aggregate result returned by {@link MemorySystem.resolveContext}. */
export interface ResolvedContext {
  /** Ordered entries, highest-priority layer first. */
  entries: MemoryEntry[];
  /** Which layers contributed at least one entry. */
  layersContributing: MemoryLayer[];
  resolvedAt: number;
}

/** Four phases executed by {@link DreamEngine.runDream}. */
export type DreamPhase = 'orient' | 'gather' | 'consolidate' | 'prune';

/** Summary written after each successful dream cycle. */
export interface DreamReport {
  runId: string;
  startedAt: number;
  completedAt: number;
  phasesExecuted: DreamPhase[];
  factsGathered: number;
  factsConsolidated: number;
  factsPruned: number;
  indexLines: number;
  indexBytes: number;
}

// ============================================================================
// Constants
// ============================================================================

/** Ordered from highest to lowest priority. */
const LAYER_PRIORITY: MemoryLayer[] = [
  'L1_managed',
  'L2_project',
  'L3_rules',
  'L4_user',
  'L5_local',
  'L6_dream',
];

const NETWORK_MD_FILENAME = 'NETWORK.md';

/** Maximum age (ms) of a memory entry before it is considered stale. */
const DEFAULT_ENTRY_TTL_MS = 30 * 24 * 60 * 60 * 1000; // 30 days

// ============================================================================
// MemorySystem
// ============================================================================

/**
 * Central memory subsystem for IOE agents.
 *
 * Responsibilities:
 * - Maintain a six-layer in-memory index of {@link MemoryEntry} objects.
 * - Persist every write as an append-only JSONL line to the correct layer
 *   shard file on disk.
 * - Replay shard files on construction so state survives process restarts.
 * - Expose {@link search} and {@link resolveContext} for context-building.
 * - Load NETWORK.md files from disk into the L2 and L5 layers.
 *
 * Thread-safety: Node.js is single-threaded; all async methods serialise
 * through the event loop. The JSONL append pattern is therefore safe without
 * additional locking.
 */
export class MemorySystem {
  /** In-memory index keyed by layer. */
  private readonly index: Map<MemoryLayer, MemoryEntry[]> = new Map(
    LAYER_PRIORITY.map(layer => [layer, []])
  );

  /** Base directory for JSONL persistence shards. */
  private readonly storageDir: string;

  /** Whether JSONL files have been replayed and the system is ready. */
  private initialised = false;

  /**
   * @param storageDir - Directory for JSONL shard files (created if absent).
   */
  constructor(storageDir: string) {
    this.storageDir = storageDir;
  }

  // --------------------------------------------------------------------------
  // Lifecycle
  // --------------------------------------------------------------------------

  /**
   * Initialise the memory system:
   * 1. Create the storage directory if it does not exist.
   * 2. Replay all existing JSONL shards into the in-memory index.
   * 3. Evict expired entries.
   */
  async init(): Promise<void> {
    if (this.initialised) return;

    await fs.promises.mkdir(this.storageDir, { recursive: true });

    for (const layer of LAYER_PRIORITY) {
      const shardPath = this._shardPath(layer);
      if (fs.existsSync(shardPath)) {
        await this._replayJSONL(shardPath, layer);
      }
    }

    this._evictExpired();
    this.initialised = true;
  }

  // --------------------------------------------------------------------------
  // NETWORK.md loading
  // --------------------------------------------------------------------------

  /**
   * Load a NETWORK.md file and insert its contents as a single L2 (project)
   * or L5 (local) memory entry.
   *
   * @param filePath - Absolute path to the NETWORK.md file.
   * @param layer    - Target layer; defaults to `'L2_project'` for a root file
   *                   and `'L5_local'` for a subdirectory file.
   */
  async loadNetworkMd(
    filePath: string,
    layer: Extract<MemoryLayer, 'L2_project' | 'L5_local'> = 'L2_project'
  ): Promise<MemoryEntry> {
    if (!fs.existsSync(filePath)) {
      throw new Error(`NETWORK.md not found at: ${filePath}`);
    }

    const content = await fs.promises.readFile(filePath, 'utf8');
    const entry: MemoryEntry = {
      id: `networkmd_${Buffer.from(filePath).toString('base64url').slice(0, 16)}`,
      layer,
      content: content.trim(),
      source: filePath,
      createdAt: Date.now(),
      updatedAt: Date.now(),
      importance: layer === 'L2_project' ? 0.95 : 0.7,
      tags: ['network_md', NETWORK_MD_FILENAME.toLowerCase()],
    };

    await this.upsert(entry);
    return entry;
  }

  /**
   * Auto-discover all NETWORK.md files under `rootDir` (up to `maxDepth`
   * directory levels deep) and load them.
   *
   * - The file at `rootDir/NETWORK.md` is loaded into L2.
   * - All others are loaded into L5.
   *
   * @param rootDir  - Repository root directory.
   * @param maxDepth - Maximum directory traversal depth (default: 6).
   */
  async discoverAndLoadNetworkMd(rootDir: string, maxDepth = 6): Promise<MemoryEntry[]> {
    const loaded: MemoryEntry[] = [];
    const queue: Array<{ dir: string; depth: number }> = [{ dir: rootDir, depth: 0 }];

    while (queue.length > 0) {
      const { dir, depth } = queue.shift()!;
      const candidate = path.join(dir, NETWORK_MD_FILENAME);

      if (fs.existsSync(candidate)) {
        const layer = dir === rootDir ? 'L2_project' : 'L5_local';
        try {
          const entry = await this.loadNetworkMd(candidate, layer);
          loaded.push(entry);
        } catch {
          // Non-fatal: continue discovering
        }
      }

      if (depth < maxDepth) {
        let children: string[] = [];
        try {
          children = await fs.promises.readdir(dir);
        } catch {
          continue;
        }
        for (const child of children) {
          const childPath = path.join(dir, child);
          try {
            const stat = await fs.promises.stat(childPath);
            if (stat.isDirectory() && !child.startsWith('.') && child !== 'node_modules') {
              queue.push({ dir: childPath, depth: depth + 1 });
            }
          } catch {
            // Skip unreadable entries
          }
        }
      }
    }

    return loaded;
  }

  // --------------------------------------------------------------------------
  // CRUD
  // --------------------------------------------------------------------------

  /**
   * Insert or update a memory entry.
   * - If an entry with the same `id` already exists in the same layer, it is
   *   replaced in the in-memory index.
   * - The new/updated entry is appended to the layer's JSONL shard.
   */
  async upsert(entry: MemoryEntry): Promise<void> {
    this._assertInit();

    const layerEntries = this.index.get(entry.layer)!;
    const existingIdx = layerEntries.findIndex(e => e.id === entry.id);

    const updated: MemoryEntry = { ...entry, updatedAt: Date.now() };

    if (existingIdx >= 0) {
      layerEntries[existingIdx] = updated;
    } else {
      layerEntries.push(updated);
    }

    await this._appendJSONL(this._shardPath(entry.layer), updated);
  }

  /**
   * Remove an entry by id from the given layer.
   * Note: removal is recorded as a tombstone appended to the JSONL shard so
   * that replay correctly suppresses the entry on restart.
   */
  async remove(id: string, layer: MemoryLayer): Promise<boolean> {
    this._assertInit();

    const layerEntries = this.index.get(layer)!;
    const idx = layerEntries.findIndex(e => e.id === id);
    if (idx < 0) return false;

    layerEntries.splice(idx, 1);

    // Tombstone record
    await this._appendJSONL(this._shardPath(layer), {
      __tombstone: true,
      id,
      layer,
      deletedAt: Date.now(),
    } as unknown as MemoryEntry);

    return true;
  }

  /** Retrieve a single entry by id, searching all layers or a subset. */
  get(id: string, layers: MemoryLayer[] = LAYER_PRIORITY): MemoryEntry | undefined {
    this._assertInit();
    for (const layer of layers) {
      const found = this.index.get(layer)?.find(e => e.id === id);
      if (found) return found;
    }
    return undefined;
  }

  // --------------------------------------------------------------------------
  // Search
  // --------------------------------------------------------------------------

  /**
   * Search the in-memory index across layers.
   *
   * Filters applied (all are ANDed):
   * - `domain`        - entry.domain must match
   * - `tags`          - entry must contain **all** requested tags
   * - `minImportance` - entry.importance must be >= this value
   * - `layers`        - restrict to these layers (default: all)
   *
   * Results are returned ordered by descending layer priority then descending
   * importance.
   *
   * @param query   - Free-text substring searched in `entry.content`.
   * @param options - Additional filter criteria.
   */
  search(query: string, options: MemorySearchOptions = {}): MemoryEntry[] {
    this._assertInit();

    const {
      domain,
      tags = [],
      minImportance = 0,
      layers = LAYER_PRIORITY,
      limit = 50,
    } = options;

    const lowerQuery = query.toLowerCase();
    const results: MemoryEntry[] = [];

    for (const layer of LAYER_PRIORITY) {
      if (!layers.includes(layer)) continue;

      for (const entry of this.index.get(layer) ?? []) {
        if (domain && entry.domain !== domain) continue;
        if (entry.importance < minImportance) continue;
        if (tags.length > 0 && !tags.every(t => entry.tags.includes(t))) continue;
        if (lowerQuery && !entry.content.toLowerCase().includes(lowerQuery)) continue;
        results.push(entry);
      }
    }

    // Sort by layer priority (index position), then by importance desc
    results.sort((a, b) => {
      const layerDiff = LAYER_PRIORITY.indexOf(a.layer) - LAYER_PRIORITY.indexOf(b.layer);
      if (layerDiff !== 0) return layerDiff;
      return b.importance - a.importance;
    });

    return results.slice(0, limit);
  }

  // --------------------------------------------------------------------------
  // Layer cascade resolution
  // --------------------------------------------------------------------------

  /**
   * Build a resolved context by cascading through all layers from L1 to L6.
   * Higher-priority layer entries shadow lower-priority entries that share the
   * same `id`. Caller receives a deduplicated, priority-ordered list.
   *
   * @param options - Optional filters forwarded to each layer's index.
   */
  resolveContext(options: MemorySearchOptions = {}): ResolvedContext {
    this._assertInit();

    const seen = new Set<string>();
    const entries: MemoryEntry[] = [];
    const layersContributing = new Set<MemoryLayer>();

    const { domain, tags = [], minImportance = 0, layers = LAYER_PRIORITY } = options;

    for (const layer of LAYER_PRIORITY) {
      if (!layers.includes(layer)) continue;

      for (const entry of this.index.get(layer) ?? []) {
        if (seen.has(entry.id)) continue; // Higher-priority layer already has this id
        if (domain && entry.domain !== domain) continue;
        if (entry.importance < minImportance) continue;
        if (tags.length > 0 && !tags.every(t => entry.tags.includes(t))) continue;

        seen.add(entry.id);
        entries.push(entry);
        layersContributing.add(layer);
      }
    }

    return {
      entries,
      layersContributing: [...layersContributing],
      resolvedAt: Date.now(),
    };
  }

  // --------------------------------------------------------------------------
  // Read-only access for DreamEngine
  // --------------------------------------------------------------------------

  /**
   * Return a shallow read-only snapshot of entries for a given layer.
   * DreamEngine uses this to inspect existing facts without mutating state.
   *
   * @internal Used by {@link DreamEngine}.
   */
  _readOnlySnapshot(layer: MemoryLayer): Readonly<MemoryEntry[]> {
    return Object.freeze([...(this.index.get(layer) ?? [])]);
  }

  /**
   * Total number of entries in the L6 dream layer.
   * @internal Used by {@link DreamEngine}.
   */
  _dreamLayerSize(): number {
    return this.index.get('L6_dream')?.length ?? 0;
  }

  // --------------------------------------------------------------------------
  // Private helpers
  // --------------------------------------------------------------------------

  private _assertInit(): void {
    if (!this.initialised) {
      throw new Error('MemorySystem.init() must be called before use.');
    }
  }

  private _shardPath(layer: MemoryLayer): string {
    return path.join(this.storageDir, `${layer}.jsonl`);
  }

  private async _replayJSONL(filePath: string, layer: MemoryLayer): Promise<void> {
    const layerEntries = this.index.get(layer)!;
    const fileStream = fs.createReadStream(filePath, { encoding: 'utf8' });
    const rl = readline.createInterface({ input: fileStream, crlfDelay: Infinity });

    for await (const line of rl) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      try {
        const record = JSON.parse(trimmed) as Record<string, unknown>;

        // Handle tombstones
        if (record.__tombstone === true) {
          const idx = layerEntries.findIndex(e => e.id === record.id);
          if (idx >= 0) layerEntries.splice(idx, 1);
          continue;
        }

        const entry = record as unknown as MemoryEntry;
        const idx = layerEntries.findIndex(e => e.id === entry.id);
        if (idx >= 0) {
          layerEntries[idx] = entry;
        } else {
          layerEntries.push(entry);
        }
      } catch {
        // Corrupted line – skip
      }
    }
  }

  private async _appendJSONL(filePath: string, record: MemoryEntry | Record<string, unknown>): Promise<void> {
    await fs.promises.appendFile(filePath, JSON.stringify(record) + '\n', 'utf8');
  }

  private _evictExpired(): void {
    const now = Date.now();
    for (const layer of LAYER_PRIORITY) {
      const layerEntries = this.index.get(layer)!;
      const before = layerEntries.length;
      const filtered = layerEntries.filter(
        e => !e.expiresAt || e.expiresAt > now
      );
      if (filtered.length !== before) {
        this.index.set(layer, filtered);
      }
    }
  }
}

// ============================================================================
// DreamEngine
// ============================================================================

/** Distributed lock record written to disk to prevent concurrent dream runs. */
interface DreamLock {
  pid: number;
  acquiredAt: number;
  host: string;
}

/** Persistent dream state written between runs. */
interface DreamState {
  lastDreamAt: number;        // Unix ms timestamp of the last completed dream
  sessionsSinceLastDream: number;
  totalDreamsRun: number;
}

/**
 * DreamEngine – autonomous memory consolidation for IOE.
 *
 * The engine enforces a **triple gate** before beginning a consolidation cycle:
 * 1. At least {@link DreamConfig.minIntervalHours} hours since the last dream.
 * 2. At least {@link DreamConfig.minSessionsSinceLastDream} agent sessions
 *    have elapsed.
 * 3. A file-system lock can be acquired (prevents concurrent runs across
 *    multiple IOE processes).
 *
 * Only if all three gates pass does the engine execute the four-phase cycle:
 *
 * **Orient** → Read the current L6 index and existing layers to understand
 * what knowledge already exists.
 *
 * **Gather** → Scan L1–L5 entries for patterns worth consolidating into L6
 * long-term memory. Produces {@link TelecomMemoryFact} records.
 *
 * **Consolidate** → Merge new facts with existing L6 entries, deduplicating
 * and updating confidence scores.
 *
 * **Prune** → Evict low-value, low-confidence, or stale L6 entries to keep
 * the index under {@link DreamConfig.maxMemoryIndexLines} lines (~25 KB).
 *
 * DreamEngine is **read-only** with respect to layers L1–L5; it only mutates
 * the L6 dream layer via the MemorySystem's public `upsert`/`remove` API.
 */
export class DreamEngine {
  private readonly memory: MemorySystem;
  private readonly config: DreamConfig;
  private readonly stateFilePath: string;
  private readonly lockFilePath: string;

  /** Maximum bytes allowed in the L6 index on disk (~25 KB). */
  private static readonly MAX_INDEX_BYTES = 25 * 1024;

  constructor(memory: MemorySystem, config: DreamConfig, stateDir: string) {
    this.memory = memory;
    this.config = config;
    this.stateFilePath = path.join(stateDir, 'dream-state.json');
    this.lockFilePath = path.join(stateDir, 'dream.lock');
  }

  // --------------------------------------------------------------------------
  // Session accounting
  // --------------------------------------------------------------------------

  /**
   * Increment the session counter. Should be called once per new IOE session.
   * This is a low-cost bookkeeping operation that can safely be called even
   * when the engine is not actively dreaming.
   */
  async recordSession(): Promise<void> {
    const state = await this._loadState();
    state.sessionsSinceLastDream += 1;
    await this._saveState(state);
  }

  // --------------------------------------------------------------------------
  // Gate check
  // --------------------------------------------------------------------------

  /**
   * Evaluate whether all three gate conditions are currently satisfied.
   *
   * @returns `true` if the engine should proceed with a dream run.
   */
  async shouldDream(): Promise<boolean> {
    const state = await this._loadState();
    const now = Date.now();
    const minIntervalMs = this.config.minIntervalHours * 60 * 60 * 1000;

    const intervalPassed = now - state.lastDreamAt >= minIntervalMs;
    const sessionsPassed = state.sessionsSinceLastDream >= this.config.minSessionsSinceLastDream;
    const lockAvailable = !fs.existsSync(this.lockFilePath);

    return intervalPassed && sessionsPassed && lockAvailable;
  }

  // --------------------------------------------------------------------------
  // Main entry point
  // --------------------------------------------------------------------------

  /**
   * Attempt to run a full dream consolidation cycle.
   *
   * If the triple gate is not satisfied, returns `null` immediately.
   * Otherwise, executes all four phases and returns a {@link DreamReport}.
   *
   * @param forceRun - Skip the gate check (useful for manual/test invocations).
   */
  async runDream(forceRun = false): Promise<DreamReport | null> {
    if (!forceRun && !(await this.shouldDream())) {
      return null;
    }

    const acquired = await this._acquireLock();
    if (!acquired) return null;

    const runId = `dream_${Date.now()}_${process.pid}`;
    const startedAt = Date.now();
    const phasesExecuted: DreamPhase[] = [];
    let factsGathered = 0;
    let factsConsolidated = 0;
    let factsPruned = 0;

    try {
      // ----- Phase 1: Orient -----------------------------------------------
      const existingL6 = this._orient();
      phasesExecuted.push('orient');

      // ----- Phase 2: Gather ------------------------------------------------
      const newFacts = this._gather();
      factsGathered = newFacts.length;
      phasesExecuted.push('gather');

      // ----- Phase 3: Consolidate -------------------------------------------
      const consolidated = await this._consolidate(newFacts, existingL6);
      factsConsolidated = consolidated;
      phasesExecuted.push('consolidate');

      // ----- Phase 4: Prune -------------------------------------------------
      factsPruned = await this._prune();
      phasesExecuted.push('prune');

      // ----- Update persistent state ----------------------------------------
      const state = await this._loadState();
      state.lastDreamAt = Date.now();
      state.sessionsSinceLastDream = 0;
      state.totalDreamsRun += 1;
      await this._saveState(state);

      const { indexLines, indexBytes } = this._measureIndex();

      return {
        runId,
        startedAt,
        completedAt: Date.now(),
        phasesExecuted,
        factsGathered,
        factsConsolidated,
        factsPruned,
        indexLines,
        indexBytes,
      };
    } finally {
      await this._releaseLock();
    }
  }

  // --------------------------------------------------------------------------
  // Phase implementations
  // --------------------------------------------------------------------------

  /**
   * Orient phase: snapshot existing L6 entries as read-only baseline.
   * Returns current dream facts keyed by their id.
   */
  private _orient(): Map<string, MemoryEntry> {
    const snapshot = this.memory._readOnlySnapshot('L6_dream');
    const map = new Map<string, MemoryEntry>();
    for (const entry of snapshot) {
      map.set(entry.id, entry);
    }
    return map;
  }

  /**
   * Gather phase: scan L1–L5 layers (read-only) and extract telecom facts.
   *
   * Extraction heuristics (simplified for deterministic behaviour without LLM):
   * - Entries tagged `fault` or `alarm` → `event_memory`
   * - Entries tagged `baseline` or `kpi` → `network_memory`
   * - Entries with `domain` matching a known DomainType → `network_memory`
   * - Entries tagged `engineer` or `operator` → `operator_memory`
   * - Entries tagged `sop` or `regulation` → `org_memory`
   */
  private _gather(): TelecomMemoryFact[] {
    const facts: TelecomMemoryFact[] = [];
    const sourceLayers: MemoryLayer[] = ['L1_managed', 'L2_project', 'L3_rules', 'L4_user', 'L5_local'];

    for (const layer of sourceLayers) {
      const entries = this.memory._readOnlySnapshot(layer);
      for (const entry of entries) {
        const type = this._classifyEntry(entry);
        if (!type) continue;

        const factId = `dream_${entry.id.slice(0, 20)}`;
        facts.push({
          id: factId,
          type,
          observedAt: new Date(entry.createdAt).toISOString(),
          summary: entry.content.slice(0, 120).replace(/\n/g, ' '),
          detail: entry.content,
          domain: entry.domain,
          confidence: Math.min(entry.importance, 1.0),
          usageCount: 0,
          tags: [...entry.tags, layer],
        });
      }
    }

    return facts;
  }

  /**
   * Consolidate phase: merge gathered facts with the existing L6 layer.
   * New facts are upserted; existing facts with the same id get their
   * confidence score averaged and usageCount incremented.
   *
   * @returns Number of facts written or updated.
   */
  private async _consolidate(
    newFacts: TelecomMemoryFact[],
    existingL6: Map<string, MemoryEntry>
  ): Promise<number> {
    let count = 0;

    for (const fact of newFacts) {
      const existing = existingL6.get(fact.id);
      let importance: number;
      let content: string;

      if (existing) {
        // Merge: average confidence, keep the longer detail, bump usage
        const prevImportance = existing.importance;
        importance = (prevImportance + fact.confidence) / 2;
        content = existing.content.length >= fact.detail.length
          ? existing.content
          : fact.detail;
      } else {
        importance = fact.confidence;
        content = fact.detail;
      }

      const entry: MemoryEntry = {
        id: fact.id,
        layer: 'L6_dream',
        domain: fact.domain,
        content,
        source: `dream_engine:${fact.type}`,
        createdAt: existing?.createdAt ?? Date.now(),
        updatedAt: Date.now(),
        importance,
        tags: [...new Set([...fact.tags, fact.type])],
      };

      await this.memory.upsert(entry);
      count++;
    }

    return count;
  }

  /**
   * Prune phase: remove low-value L6 entries until the index is within
   * {@link DreamConfig.maxMemoryIndexLines} lines and
   * {@link DreamEngine.MAX_INDEX_BYTES} bytes.
   *
   * Pruning order: lowest importance first, ties broken by oldest updatedAt.
   *
   * @returns Number of entries pruned.
   */
  private async _prune(): Promise<number> {
    let pruned = 0;
    let { indexLines, indexBytes } = this._measureIndex();

    if (
      indexLines <= this.config.maxMemoryIndexLines &&
      indexBytes <= DreamEngine.MAX_INDEX_BYTES
    ) {
      return 0;
    }

    // Get current L6 entries sorted: lowest importance first
    const snapshot = [...this.memory._readOnlySnapshot('L6_dream')];
    snapshot.sort((a, b) => {
      const impDiff = a.importance - b.importance;
      if (impDiff !== 0) return impDiff;
      return a.updatedAt - b.updatedAt; // older first
    });

    for (const entry of snapshot) {
      if (
        indexLines <= this.config.maxMemoryIndexLines &&
        indexBytes <= DreamEngine.MAX_INDEX_BYTES
      ) {
        break;
      }

      await this.memory.remove(entry.id, 'L6_dream');
      pruned++;

      // Recompute approximate remaining size
      indexLines -= 1;
      indexBytes -= Buffer.byteLength(JSON.stringify(entry), 'utf8') + 1;
    }

    return pruned;
  }

  // --------------------------------------------------------------------------
  // Private helpers
  // --------------------------------------------------------------------------

  /**
   * Classify a memory entry into a {@link TelecomMemoryType}.
   * Returns `null` if the entry does not warrant dreaming.
   */
  private _classifyEntry(entry: MemoryEntry): TelecomMemoryType | null {
    const tags = entry.tags.map(t => t.toLowerCase());
    const content = entry.content.toLowerCase();

    if (
      tags.some(t => ['fault', 'alarm', 'incident', 'outage', 'fix', 'remediation'].includes(t)) ||
      content.includes('fault') || content.includes('alarm') || content.includes('outage')
    ) {
      return 'event_memory';
    }

    if (
      tags.some(t => ['baseline', 'kpi', 'threshold', 'pattern', 'topology'].includes(t)) ||
      entry.domain !== undefined
    ) {
      return 'network_memory';
    }

    if (
      tags.some(t => ['engineer', 'operator', 'preference', 'escalation'].includes(t)) ||
      content.includes('prefer') || content.includes('engineer')
    ) {
      return 'operator_memory';
    }

    if (
      tags.some(t => ['sop', 'regulation', 'compliance', 'change_freeze', 'procedure'].includes(t)) ||
      content.includes('regulation') || content.includes('sop')
    ) {
      return 'org_memory';
    }

    // Default: entries with sufficient importance are worth keeping as network memory
    if (entry.importance >= 0.7) {
      return 'network_memory';
    }

    return null;
  }

  /**
   * Measure the current L6 index size in lines and approximate bytes by
   * summing serialised entry lengths.
   */
  private _measureIndex(): { indexLines: number; indexBytes: number } {
    const entries = this.memory._readOnlySnapshot('L6_dream');
    let indexBytes = 0;
    for (const entry of entries) {
      indexBytes += Buffer.byteLength(JSON.stringify(entry), 'utf8') + 1; // +1 for newline
    }
    return { indexLines: entries.length, indexBytes };
  }

  private async _loadState(): Promise<DreamState> {
    try {
      const raw = await fs.promises.readFile(this.stateFilePath, 'utf8');
      return JSON.parse(raw) as DreamState;
    } catch {
      return { lastDreamAt: 0, sessionsSinceLastDream: 0, totalDreamsRun: 0 };
    }
  }

  private async _saveState(state: DreamState): Promise<void> {
    await fs.promises.writeFile(this.stateFilePath, JSON.stringify(state, null, 2), 'utf8');
  }

  private async _acquireLock(): Promise<boolean> {
    if (fs.existsSync(this.lockFilePath)) {
      // Check if lock is stale (> 2h old)
      try {
        const raw = await fs.promises.readFile(this.lockFilePath, 'utf8');
        const lock = JSON.parse(raw) as DreamLock;
        const age = Date.now() - lock.acquiredAt;
        if (age < 2 * 60 * 60 * 1000) return false; // Fresh lock: respect it
        // Stale lock: overwrite
      } catch {
        // Corrupted lock file: overwrite
      }
    }

    const lock: DreamLock = {
      pid: process.pid,
      acquiredAt: Date.now(),
      host: process.env.HOSTNAME ?? 'unknown',
    };

    try {
      await fs.promises.writeFile(this.lockFilePath, JSON.stringify(lock), 'utf8');
      return true;
    } catch {
      return false;
    }
  }

  private async _releaseLock(): Promise<void> {
    try {
      await fs.promises.unlink(this.lockFilePath);
    } catch {
      // Lock file may have already been cleaned up
    }
  }
}
